# Fundaments

### 1. Creating numpy array
- We can create numpy array by using array(p) function.
- Internally it creates object to ndarray
- We can pass list, tuple etc as a parameter to the array(p) Function.
- Having same type of values is recommended

### 2 numpy.ndim
- Ndim is predefined variable in numpy
- By using this we can check the array dimensions.

In [1]:
# creating numpy array with single values

import numpy as np

age=44
value=np.array(age)

print(value)
print(type(value))
print(value.ndim)

44
<class 'numpy.ndarray'>
0


In [2]:
# Creating numpy array with group of values

import numpy as np

n=[10,20,30,40,50]
sales=np.array(n)

print(sales)
print(type(sales))
print(sales.ndim)

[10 20 30 40 50]
<class 'numpy.ndarray'>
1


In [3]:
# Creating numpy array with group of values

import numpy as np

a=[1,2,3,4,5]
n=np.array(a)

print(n)
print(type(n))
print(n.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [5]:
# Creating numpy array with group of values

import numpy as np

details=[[1,2],[30,40]]
sales=np.array(details)

print(sales)
print(type(sales))
print(sales.ndim)

[[ 1  2]
 [30 40]]
<class 'numpy.ndarray'>
2


In [7]:
# Creating numpy array with group of values

import numpy as np

details=[[1,2],[30,40],[30,23]]
sales=np.array(details)

print(sales)
print(type(sales))
print(sales.ndim)

[[ 1  2]
 [30 40]
 [30 23]]
<class 'numpy.ndarray'>
2


In [8]:
# Creating numpy array with group of values

import numpy as np

details=[[1,2,3],[30,40,50],[30,23,50]]
sales=np.array(details)

print(sales)
print(type(sales))
print(sales.ndim)

[[ 1  2  3]
 [30 40 50]
 [30 23 50]]
<class 'numpy.ndarray'>
2


In [18]:
#
import pandas as pd
import numpy as np

df=pd.read_csv('/Users/apple/Downloads/iris.csv')
print(df.values)
print(type(df))

[[5.1 3.5 1.4 0.2 'setosa']
 [4.9 3.0 1.4 0.2 'setosa']
 [4.7 3.2 1.3 0.2 'setosa']
 [4.6 3.1 1.5 0.2 'setosa']
 [5.0 3.6 1.4 0.2 'setosa']
 [5.4 3.9 1.7 0.4 'setosa']
 [4.6 3.4 1.4 0.3 'setosa']
 [5.0 3.4 1.5 0.2 'setosa']
 [4.4 2.9 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.4 3.7 1.5 0.2 'setosa']
 [4.8 3.4 1.6 0.2 'setosa']
 [4.8 3.0 1.4 0.1 'setosa']
 [4.3 3.0 1.1 0.1 'setosa']
 [5.8 4.0 1.2 0.2 'setosa']
 [5.7 4.4 1.5 0.4 'setosa']
 [5.4 3.9 1.3 0.4 'setosa']
 [5.1 3.5 1.4 0.3 'setosa']
 [5.7 3.8 1.7 0.3 'setosa']
 [5.1 3.8 1.5 0.3 'setosa']
 [5.4 3.4 1.7 0.2 'setosa']
 [5.1 3.7 1.5 0.4 'setosa']
 [4.6 3.6 1.0 0.2 'setosa']
 [5.1 3.3 1.7 0.5 'setosa']
 [4.8 3.4 1.9 0.2 'setosa']
 [5.0 3.0 1.6 0.2 'setosa']
 [5.0 3.4 1.6 0.4 'setosa']
 [5.2 3.5 1.5 0.2 'setosa']
 [5.2 3.4 1.4 0.2 'setosa']
 [4.7 3.2 1.6 0.2 'setosa']
 [4.8 3.1 1.6 0.2 'setosa']
 [5.4 3.4 1.5 0.4 'setosa']
 [5.2 4.1 1.5 0.1 'setosa']
 [5.5 4.2 1.4 0.2 'setosa']
 [4.9 3.1 1.5 0.1 'setosa']
 [5.0 3.2 1.2 0.2 's

### 3 Indexing and Slicing 
- We can access numpy array values by using indexing and slicing
- Numpy array having indexing nature
- Numpy array index start with 0
  1. First elements stores in 0th index
  2. Second elements stores in 1th index etc
- By using slicing we can access piece of array from the main array

In [19]:
# Accessing numpy array by using indexing 

import numpy as np 
d=[10,20,30,40,50]
s=np.array(d)

print(s[0])
print(s[1])
print(s[2])

10
20
30


In [20]:
# Accessing numpy array by using indexing 

import numpy as np

d=[10,20,30,40,50]
s=np.array(d)

print(d)
print(s[2:])

[10, 20, 30, 40, 50]
[30 40 50]


In [25]:
# Creating matrix and selecting elements

import numpy as np

m=np.array([[10,20,30],[40,50,60],[70,80,90]])

print(m)

print(m[0,0])
print(m[0,1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20


### Index Error
- If we try to access value with out of bounds of index then we will get IndexError

In [28]:
# Accessing numpy array values

import numpy as np
d=[10,12,14,16,18]
s=np.array(d)

print(s[22])

IndexError: index 22 is out of bounds for axis 0 with size 5

### 4 Creating a array with all zeros 
- We can create array with all zeros by using numpy.zeros()function

In [30]:
# Creating numpy array with group of values

import numpy as np

sales=np.zeros(5)

print(sales)
print(type(sales))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


### 5 Creating a array with all ones
- We can create array with all ones by using numpy.ones()function

In [32]:
# Creating numpy array with group of values

import numpy as np

sales=np.ones(5)

print(sales)
print(type(sales))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
