# 3 Numpy ATRIBUTES

### 1. Numpy Array Attributes
- Numpy array having predefined attributes to helps to understand the essentials functionality

### 2. shape attribute
- shape is a predefined attributes in numpy array.
- We should access this shape attribute by using numpy array object
- By using this we can check number of rows and columns in an array
- Shape attribute returns the tuple as number of rows and column

In [2]:
# Creating numpy array with group of values

import numpy as np

a=[[1,2],[3,4],[5,6]]
s=np.array(a)

print(s)
print(s.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


### 3 ndim attribute
- ndim is a predefined attribute in numpy array.
- We should access this ndim attribute by using numpy array object
- By using this we can check the dimensions of an array

In [4]:
# Creating numpy array check with ndim attribute

import numpy as np

d=[10,20,30,40,50]
s=np.array(d)

print(s)
print(s.ndim)

[10 20 30 40 50]
1


### 4 arrayobject.T
- T is a predefined attribute in numpy array.
- We should access this T attribute by using numpy array object
- By using this we can transpose the array means it convers rows as columns and columns as rows

In [12]:
# T attribute
import numpy as np

d=[[10,20,30],[40,50,60]]
s=np.array(d)
print(d)
print()
print()
print(s.T)

[[10, 20, 30], [40, 50, 60]]


[[10 40]
 [20 50]
 [30 60]]
