# 4 Numpy - important methods

### 1 Numpy Array methods
- Numpy array having predefined method to preform different operations over array

### 2 min() method
- min() is a predefined method in numpy array
- We should access this min() method by using numpy array object
- By using this we can check minimum value from the array

In [2]:
# min() method
import numpy as np
d=[[10,20,30],[40,30,23]]
s=np.array(d)

print(d)
print()
print(s.min())

[[10, 20, 30], [40, 30, 23]]

10


In [4]:
# min() method
import numpy as np
d=np.array([[10,20,30],[40,30,23]])
s=np.array(d)

print(d)
print()
print(s.min())

[[10 20 30]
 [40 30 23]]

10


### 3 Max method
- max() is a predifined method in numpy array
- We should access this max() method by using numpy array object
- By using this we can check maximum value from the array

In [5]:
# Max method

import numpy as np

d=np.array([[10,23,45,66],[23,43,24,52]])
s=np.array(d)

print(d)
print()
print(s.max())


[[10 23 45 66]
 [23 43 24 52]]

66


# 4 sum() method
- sum() is a predefined method in numpy array we should access this method by using numpy array object
- By using this we can get sum of all values from array

In [7]:
# sum method

import numpy as np

d=np.array([[10,30,40],[43,53,53]])
s=np.array(d)

print(d)
print()
print(s.sum())

[[10 30 40]
 [43 53 53]]

229


### 5 reshape()method  imp
- reshape() is a predefined method in numpy array
- We should access this method by using numpy array object
- By using this we can change the shape of on array
  

In [16]:
# reshape()method

import numpy as np
d=np.array([[10,20,30],[40,50,60]])
s=np.array(d)

print(d)
print()
print(s.reshape(3,2))

[[10 20 30]
 [40 50 60]]

[[10 20]
 [30 40]
 [50 60]]


In [17]:
import numpy as np
d=np.array([[10,20,30],[40,50,60]])
s=np.array(d)

print(d)
print()
print(s.reshape(1,6))

[[10 20 30]
 [40 50 60]]

[[10 20 30 40 50 60]]


In [18]:
import numpy as np
d=np.array([[10,20,30],[40,50,60]])
s=np.array(d)

print(d)
print()
print(s.reshape(6,1))

[[10 20 30]
 [40 50 60]]

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


### 6.count_nonzero(p) function
- count_nonzero(p) is a predefined function in numpy array
- We should access this function by using numpy
- By using this we can get non zero values from numpy

In [20]:
# count_nonzero(p) function

import numpy as np

d=np.array([[10,0,30],[40,50,0]])
s=np.array(d)

print(d)
print()
print(np.count_nonzero(s))

[[10  0 30]
 [40 50  0]]

4


### 7 sort() method
- sort() is a predefined method in numpy array
- We should access this method by using numpy array object
- by using this we can aort values in array
  

In [26]:
# sort() method

import numpy as np
d=np.array([[55,13,12],[99,2,1]])
s=np.array(d)

print(s)
s.sort()

print()

print(s)


[[55 13 12]
 [99  2  1]]

[[12 13 55]
 [ 1  2 99]]


### 8 flatten() method
- flatten() is a predefined method in numpy array
- We should access this method by using numpy array object
- This method keeps all values in one dimension array

In [28]:
# Flatten() method

import numpy as np

d=np.array([[10,20,30],[40,50,60]])
s=np.array(d)

print(s)
print()
print(s.flatten())

[[10 20 30]
 [40 50 60]]

[10 20 30 40 50 60]


### 9 . adding value to array of values
- based on requirement we can add value to array of values.


In [29]:
# Adding value to array of values

import numpy as np
d=np.array([[10,20,30],[40,50,60]])
s=np.array(d)
print(s)
print()
print(s+2)

[[10 20 30]
 [40 50 60]]

[[12 22 32]
 [42 52 62]]


### 10 Diagonal of a matrix
- Diagonal elements of a matrix

In [32]:
# Diagonal()  matrix 

import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)
print()
print(matrix.diagonal())


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 5 9]


### 11 Trace of a matrix
- The trace of a matrix is the sum of the diagonal elements

In [33]:
# Trace of the matrix

import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)
print()
print(matrix.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

15


In [34]:
# Trace of the matrix

import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(matrix)
print()
print(sum(matrix.diagonal()))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

15


### 12 Adding and subtracting matrices
- we can add and subtract two matrics
- We need to call and subtract functions

In [36]:
# Adding two matrices

import numpy as np

m_a=np.array([[1,1,1],[1,1,1],[1,1,2]])
m_b=np.array([[1,3,1],[1,3,1],[1,3,8]])

print(m_a)
print()
print(m_b)
print()
print('add')
print(np.add(m_a,m_b))

[[1 1 1]
 [1 1 1]
 [1 1 2]]

[[1 3 1]
 [1 3 1]
 [1 3 8]]

add
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [38]:
# subtract two matrices
import numpy as np

m_a=np.array([[1,1,1],[1,1,1],[1,1,2]])
m_b=np.array([[1,3,1],[1,3,1],[1,3,8]])

print(m_a)
print()
print(m_b)
print()
print('add')
print(np.subtract(m_a,m_b))

[[1 1 1]
 [1 1 1]
 [1 1 2]]

[[1 3 1]
 [1 3 1]
 [1 3 8]]

add
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


In [43]:
# Adding two matrices

import numpy as np

m_a=np.array([[1,1,1],[1,1,1],[1,1,2]])
m_b=np.array([[1,3,1],[1,3,1],[1,3,8]])

print(m_a)
print()
print(m_b)
print()
print('add')
print(m_a + m_b)

[[1 1 1]
 [1 1 1]
 [1 1 2]]

[[1 3 1]
 [1 3 1]
 [1 3 8]]

add
[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


In [41]:
# subtract two matrices
import numpy as np

m_a=np.array([[1,1,1],[1,1,1],[1,1,2]])
m_b=np.array([[1,3,1],[1,3,1],[1,3,8]])

print(m_a)
print()
print(m_b)
print()
print('sub')
print(m_a - m_b)


[[1 1 1]
 [1 1 1]
 [1 1 2]]

[[1 3 1]
 [1 3 1]
 [1 3 8]]

sub
[[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]
